### ISSUE TITLE
Assumes the string is UTF-8, which it my not be

### ISSUE THREAD

**Issue by brian-learningpool** [feross/string-to-stream#6]
The line of code at https://github.com/feross/string-to-stream/blob/master/index.js#L18 assumes that the encoding on the Buffer is a `UTF8` string.  There are instances where it might be a binary string or any other type of encoding.

I think the constructor should accept an optional encoding and default to `UTF8` if it's not set.

**Comment by feross** [comment]
Released as 3.0.0.
